BUS-4655 Criar as classes e atributos
PeixotoLucass/projeto-netflix pull request #1
Opened 2022-09-13 20:07 UTC by PeixotoLucass

:memo: Changelog
> O que essa mudança altera?
Alteração para criação das tabelas por comandos SQL.

:balloon: Motivação
> Por que faremos essa alteração?
Alteração feita para criação de tabelas.

2022-09-14 14:15 UTC, felipemandu commented on src/main/resources/sql/CriacaoDeTabelas.sql
> +                            USER_ID INTEGER PRIMARY KEY NOT NULL, USER_TYPE varchar(30)
Creio que é interessante o user type ter uma descrição também.
um field do tipo string, com o nome.
Se é user, superUser.
porque ai já ficam junto a chave que representa o user_type e a descrição do que é aquele user type

2022-09-14 14:18 UTC, felipemandu commented on src/main/resources/sql/CriacaoDeTabelas.sql
> +);
fiquei com duvida aqui, se não deveria haver um campo que representasse de qual titulo esse cast pertence.
porque o elenco é por titulo, mas dessa forma, diferentes titulos poderiam ter o mesmo elenco.

2022-09-14 14:19 UTC, felipemandu commented on src/main/resources/sql/CriacaoDeTabelas.sql
> +                        TITLE_ID INTEGER PRIMARY KEY NOT NULL, CLASSIFICATION VARCHAR(30), LAUNCH DATE,
nos padrões da pags seria IDT_TITLE

2022-09-14 14:19 UTC, felipemandu commented on src/main/resources/sql/CriacaoDeTabelas.sql
> +                        TITLE_ID INTEGER PRIMARY KEY NOT NULL, CLASSIFICATION VARCHAR(30), LAUNCH DATE,
DAT_LAUNCH

2022-09-14 14:19 UTC, felipemandu commented on src/main/resources/sql/CriacaoDeTabelas.sql
> +                        TITLE_NAME VARCHAR(50),
DES_TITLE_NAME

2022-09-14 14:20 UTC, felipemandu commented on src/main/resources/sql/CriacaoDeTabelas.sql
> +                        DURATION VARCHAR(30),
VAL_DURATION

2022-09-14 14:20 UTC, felipemandu commented on src/main/resources/sql/CriacaoDeTabelas.sql
> +                        DURATION VARCHAR(30),
https://confluence.intranet.uol.com.br/confluence/pages/viewpage.action?pageId=50525950

2022-09-14 14:20 UTC, felipemandu commented on src/main/resources/sql/CriacaoDeTabelas.sql
> +                        TITLE_NAME VARCHAR(50),
https://confluence.intranet.uol.com.br/confluence/pages/viewpage.action?pageId=50525950

2022-09-14 14:20 UTC, felipemandu commented on src/main/resources/sql/CriacaoDeTabelas.sql
> +                        TITLE_ID INTEGER PRIMARY KEY NOT NULL, CLASSIFICATION VARCHAR(30), LAUNCH DATE,
https://confluence.intranet.uol.com.br/confluence/pages/viewpage.action?pageId=50525950

2022-09-14 14:23 UTC, felipemandu commented on src/main/resources/application.yaml
> +    username: testebd
isso estamos tentando mudar.
é má prática e erro colocar esses valores no github
o que colocamos seria uma ENV que definimos na hora da execução da aplicação.

 url: ${DB_ADDRESS}
 username: ${DB_USERNAME}
password: ${DB_PASSWORD}

ai. na hora de executar a aplicação você tem esses dados, mas se invadirem seu github não conseguem pegar

2022-09-14 14:23 UTC, felipemandu requested changes
fiz uns comentáriios

2022-09-14 14:27 UTC, felipemandu reviewed
Tem uma questão com o nome do arquivo sql tbm.

meio padrão aqui

snake case com upper case.
nome do arquivo em inglês
e um numero da ordem do script na frente.

1_TABLE_CREATION.sql.

Ai, um próximo script ta ordenado.

2_INDEX_CREATION_TABLE_TITLE.sql

2022-09-14 14:33 UTC, PeixotoLucass commented on src/main/resources/sql/CriacaoDeTabelas.sql
> +                        TITLE_ID INTEGER PRIMARY KEY NOT NULL, CLASSIFICATION VARCHAR(30), LAUNCH DATE,
Irei revisar os pontos citados e fazer as correções.

2022-09-14 14:45 UTC, PeixotoLucass commented
Estou fazendo as alterações.

2022-09-14 15:38 UTC, PeixotoLucass commented on src/main/resources/sql/CriacaoDeTabelas.sql
> +                            USER_ID INTEGER PRIMARY KEY NOT NULL, USER_TYPE varchar(30)
Esse campo USER_TYPE é a descrição, se ele é user ou se ele é superUser.

2022-09-14 19:05 UTC, felipemandu commented on src/main/resources/sql/1_CREATE_TABLES.sql
> +CREATE TABLE IDT_USER_TYPE (
mano. ta errado isso aqui.
não era o nome das tabelas os padrões, mas sim o nome dos campos

2022-09-15 11:57 UTC, PeixotoLucass commented on src/main/resources/sql/1_CREATE_TABLES.sql
> +CREATE TABLE IDT_USER_TYPE (
Blz, agora vai ficar certo

2022-09-15 13:27 UTC, felipemandu commented on src/main/resources/sql/1_CREATE_TABLES.sql
> +                        LOGIN VARCHAR(50),
nam_login

2022-09-15 13:27 UTC, felipemandu commented on src/main/resources/sql/1_CREATE_TABLES.sql
> +                        PASSWORD VARCHAR(50),
cod_password

2022-09-15 13:27 UTC, felipemandu commented on src/main/resources/sql/1_CREATE_TABLES.sql
> +                        USER_ID INTEGER,
idt_user

2022-09-15 13:27 UTC, felipemandu commented on src/main/resources/sql/1_CREATE_TABLES.sql
> +                        CONSTRAINT USER_PERSON_FK FOREIGN KEY(USER_ID) REFERENCES USER_TYPE(IDT_USER_ID)
idt_user

2022-09-15 13:27 UTC, felipemandu commented on src/main/resources/sql/1_CREATE_TABLES.sql
> +                        	IDT_USER_ID INTEGER PRIMARY KEY NOT NULL, USER_TYPE VARCHAR(30)
idt_user

2022-09-15 13:28 UTC, felipemandu commented on src/main/resources/sql/1_CREATE_TABLES.sql
> +                        AGE_ACTOR INTEGER
num_age_actor

2022-09-15 13:28 UTC, felipemandu commented on src/main/resources/sql/1_CREATE_TABLES.sql
> +                            ACTOR_ID INTEGER,
idt_actor

2022-09-15 13:28 UTC, felipemandu commented on src/main/resources/sql/1_CREATE_TABLES.sql
> +                            CONSTRAINT NAME_CAST_ACTOR_FK FOREIGN KEY(ACTOR_ID) REFERENCES ACTOR(IDT_ACTOR_ID),
idt_actor

2022-09-15 13:28 UTC, felipemandu commented on src/main/resources/sql/1_CREATE_TABLES.sql
> +                            TITLE_ID INTEGER
idt_title

2022-09-15 13:28 UTC, felipemandu commented on src/main/resources/sql/1_CREATE_TABLES.sql
> +                       		IDT_DIRECTOR_ID INTEGER PRIMARY KEY NOT NULL,
idt_director

2022-09-15 13:28 UTC, felipemandu commented on src/main/resources/sql/1_CREATE_TABLES.sql
> +                            DIRECTOR_ID INTEGER,
idt_director

2022-09-15 13:28 UTC, felipemandu commented on src/main/resources/sql/1_CREATE_TABLES.sql
> +                            CONSTRAINT DIRECTION_DIRECTOR_FK FOREIGN KEY(DIRECTOR_ID) REFERENCES DIRECTOR(IDT_DIRECTOR_ID)
idt_director

2022-09-15 13:29 UTC, felipemandu commented on src/main/resources/sql/1_CREATE_TABLES.sql
> +                        DIRECTION_ID INTEGER,
idt_direction

2022-09-15 13:29 UTC, felipemandu commented on src/main/resources/sql/1_CREATE_TABLES.sql
> +                    	IDT_TITLE_ID INTEGER PRIMARY KEY NOT NULL, CLASSIFICATION VARCHAR(30), LAUNCH DATE,
dat_launch

2022-09-15 13:29 UTC, felipemandu commented on src/main/resources/sql/1_CREATE_TABLES.sql
> +                    	IDT_TITLE_ID INTEGER PRIMARY KEY NOT NULL, CLASSIFICATION VARCHAR(30), LAUNCH DATE,
idt_title

2022-09-15 13:29 UTC, felipemandu commented on src/main/resources/sql/1_CREATE_TABLES.sql
> +                            PERSON_ID INTEGER,
idt_person

2022-09-15 13:29 UTC, felipemandu commented on src/main/resources/sql/1_CREATE_TABLES.sql
> +                            CONSTRAINT HISTORY_PERSON_FK FOREIGN KEY(PERSON_ID) REFERENCES PERSON(IDT_PERSON_ID),
idt_person

2022-09-15 13:30 UTC, felipemandu commented on src/main/resources/sql/1_CREATE_TABLES.sql
> +                            TITLE_ID INTEGER,
idt_title

2022-09-15 13:30 UTC, felipemandu commented on src/main/resources/sql/1_CREATE_TABLES.sql
> +                            CONSTRAINT HISTORY_TITLE_FK FOREIGN KEY(TITLE_ID) REFERENCES TITLE(IDT_TITLE_ID)
idt_title

2022-09-15 13:30 UTC, felipemandu commented on src/main/resources/sql/1_CREATE_TABLES.sql
> +            FOREIGN KEY(TITLE_ID) REFERENCES TITLE(IDT_TITLE_ID)
idt_title

2022-09-15 13:32 UTC, felipemandu commented on src/main/resources/sql/1_CREATE_TABLES.sql
> +                     	IDT_PERSON_ID INTEGER PRIMARY KEY NOT NULL,
não é assim que definimos primary key
IDT_PERSON_ID INTEGER NOT NULL

ai depois
CONSTRAINT PERSON_PK PRIMARY KEY (IDT_PERSON)

2022-09-15 13:34 UTC, felipemandu commented on src/main/resources/sql/1_CREATE_TABLES.sql
> +                        CONSTRAINT USER_PERSON_FK FOREIGN KEY(USER_ID) REFERENCES USER_TYPE(IDT_USER_ID)
CONSTRAINT USER_PERSON_FK
seria
CONSTRAINT PERSON_USER_FK
primeiro a tabela atual, depois a tabela que referencia

2022-09-15 13:34 UTC, felipemandu commented on src/main/resources/sql/1_CREATE_TABLES.sql
> +                    	IDT_ACTOR_ID INTEGER PRIMARY KEY NOT NULL,
tira o primary key e faz virar um constraint

2022-09-15 13:35 UTC, felipemandu commented on src/main/resources/sql/1_CREATE_TABLES.sql
> +                    	IDT_GENRE_ID INTEGER PRIMARY KEY NOT NULL,
idt_genre
tira o primary key e faz virar um constraint

2022-09-15 13:36 UTC, felipemandu commented on src/main/resources/sql/1_CREATE_TABLES.sql
> +                            IDT_HISTORY_ID INTEGER PRIMARY KEY NOT NULL,
idt_history
tirar primary key daqui e criar constraint

2022-09-15 13:38 UTC, felipemandu commented on src/main/resources/sql/1_CREATE_TABLES.sql
> +                        	IDT_USER_ID INTEGER PRIMARY KEY NOT NULL, USER_TYPE VARCHAR(30)
user_type estava na mesma linha, nem tinha visto
dá um enter aqui
e seria des_user_type

2022-09-15 13:42 UTC, felipemandu commented on src/main/resources/sql/1_CREATE_TABLES.sql
> +                    	IDT_TITLE_ID INTEGER PRIMARY KEY NOT NULL, CLASSIFICATION VARCHAR(30), LAUNCH DATE,
des_classification?
esse classification é tipo um enum?

2022-09-19 12:15 UTC, gabcunha approved these changes

2022-09-19 13:48 UTC, felipemandu approved these changes

2022-09-19 14:04 UTC, merged